global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'arithmetic_app'
    static_configs:
      - targets: ['host.docker.internal:5000']
